### PR TITLE
Color fix

### PR DESCRIPTION
**Pull request by thecakeisfalse**
Fixed banner error

```
   ___ ___       __   _______       __       __ __
  |   Y   .---.-|  |_|   _   .-----|  .-----|__|  |_
  |%grey.  |   |  _  |   _|   |___|  _  |  |  _  |  |   _|
  |%grey.  _   |___._|____|____   |   __|__|_____|__|____|
  |%grey:  |   |          |%grey:  |   |__|
  |%grey::.|%grey:. |          |%grey::.. . |
  `--- ---'          `-------'

    --=( HatSploit Framework Lic1575 v1.5.0
--==--=( Developed by EntySec (https://entysec.netlify.app/)
    --=( 19 payloads | 30 modules | 1 plugins

HatSploit Tip: Use jobs -k to kill broken job manualy

(hsf)> 

```

### CODE REVIEW

**Comment by thecakeisfalse** [comment]
@enty8080

**Comment by thecakeisfalse** [comment]
@enty8080

**Comment by thecakeisfalse** [comment]
@enty8080

**Comment by enty8080** [comment]
Hello, @thecakeisfalse 

Thank you for opening this Pull Request, but unfortunately we can not perform merge operations now. This is because we are working on staged payloads. 

Come back when we finish repairing framework core.

Best regards,
Ivan Nikolsky

**Comment by thecakeisfalse** [comment]
@enty8080 Bruh

**Pull request closed without merging**
